# Vectorization

## Lists

In [171]:
a = [1, 2, 3, 4]
b = ["5", "6", "7", "8"]

In [172]:
a + b

[1, 2, 3, 4, '5', '6', '7', '8']

## Numpy

In [173]:
import numpy as np

In [174]:
a = np.array([1, 2, 3, 4])
b = np.array([5., 6., 7., 8.])
c = np.array(["1"])
d = np.array([5, 2])
e = np.array([5])

In [175]:
a + b

array([ 6.,  8., 10., 12.])

In [176]:
a + c

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int64'), dtype('<U1')) -> None

In [ ]:
a + d

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [ ]:
a + e

array([6, 7, 8, 9])

In [ ]:
a = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

In [ ]:
np.shape(a)

(3, 3)

In [ ]:
np.identity(3) * a

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [ ]:
np.matmul(np.identity(3), a)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
a = np.reshape(a, 9)

In [ ]:
a.shape

(3, 3)

In [ ]:
a = np.reshape(a, (3, 3))

In [179]:
np.ones_like(a) * 5

array([5, 5, 5, 5])

## PyTorch

In [ ]:
import torch

In [ ]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])

In [ ]:
a + b

tensor([ 6,  8, 10, 12])

In [ ]:
a = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

In [ ]:
print(a.shape)
print(a.dtype)
print(a.device)
print(a.layout)

torch.Size([3, 3])
torch.float32
cpu
torch.strided


In [ ]:
torch.eye(3) * a

tensor([[1., 0., 0.],
        [0., 5., 0.],
        [0., 0., 9.]])

In [ ]:
torch.matmul(torch.eye(3), a)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
b = torch.tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 1

In [ ]:
print(a.shape)
print(b.shape)

torch.Size([3, 3])
torch.Size([9])


In [ ]:
a = a.reshape(9)

In [ ]:
print(a.shape)
print(b.shape)

torch.Size([9])
torch.Size([9])


In [ ]:
a + b

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])

In [ ]:
a = a.reshape(3, 3)

In [ ]:
a

In [ ]:
a = torch.tensor([1, 2, 3, 4])

In [ ]:
a = a.unsqueeze(1)

In [ ]:
a = a.reshape(1, 9)

In [ ]:
a.squeeze(0)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

In [ ]:
c = torch.broadcast_to(torch.tensor([5]), a.shape)

In [ ]:
c 


tensor([5, 5, 5])

## .NET

[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATABgLABQ2AjIRjgAQbEB0AMgJYB2AjgNxmXU0ByArgFsYUBmADOHIl1oAlPkwAuDITQCSi4RAAOAZWEA3UTAmFC+gIZQKYiHyhgYFALwUAok0HDzwADYwaMuZMAOYwABQ4ADQUxDg4AJQ0ACoQAIJQUOYAnmHxkmTEAJxhNnYONDqCuXkFxaX2/pUCAGowYArQDABeMAAm1flEAMxUxEhUWG4ICjBMYgwQc4QA3oQU61Qj1ONJFE0APEkAfGEKABYMYhRJANoAuta2DfFrG28A7mfCjrsg1gpQPjtaKqVK9XoMJSLADyWi8HSgYkO0SSKKOILBEKU+hgql6syUCiyyOuR1e61WBDebwsVjEgmc1xomMhDBxeIJkKykmpGwAZtAYOYwGcKGFaRQLD4+I5mI8yjAXlTeRRKSrqSK2gBrPqq6wMgDULilMrYFAAvuTqZblbyMAB2fUCHkbG1vK0YLZja57QStdqdHq9Q4nc6Xa73eXPK0fL6wH1/MQAoEKDHg1kwuGZBFI1HXNFprFs3H4xRcknHK1qlUS+kCRlJZnp7ElzlEl28hh8sL+hFqMQACUsvXelhgqTADj82d1ADJZ1HynRZsFzhQjhRe9AQzQAMK2RRK9XV9XrCU4gOIxkAWRgAmgWWvljEZ3MPj35iTJK3UBDJ3qDg1Lap4xjWlhOj+jI/juABamgdqeAqwMKophLAfIUMhvSLD4WSSuBF4IhQcqEdAYhHqevJ1pBRqSm0CKDJR6x1lB9HQBUVTUWxUBAUx+FWLAAjmMw+JWC4AH+MuIRrgApJu3E7vu8gKAh6oSYyEk3AAeoJwlMKJNA0HcqmuqB6xIUKIpiueb4ysRTCLoqZmqs5byamAOq9HqLG0SaMBmm6KqBXajp1ghNrmkAA==)